(function (root) {
  "use strict";
  const TIME_ZONE = Intl.DateTimeFormat().resolvedOptions().timeZone || "America/Chicago";
  function stationParts(date) { const parts=new Intl.DateTimeFormat("en-US",{timeZone:TIME_ZONE,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(date); return Object.fromEntries(parts.filter(part=>part.type!=="literal").map(part=>[part.type,Number(part.value)])); }
  function zonedToUtc(year,month,day,hour=0,minute=0,second=0) { const target=Date.UTC(year,month-1,day,hour,minute,second); let guess=target; for(let i=0;i<4;i+=1){const p=stationParts(new Date(guess));const represented=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second);guess+=target-represented;} return guess; }
  function dateKey(nowMs){const p=stationParts(new Date(nowMs));return `${p.year}-${String(p.month).padStart(2,"0")}-${String(p.day).padStart(2,"0")}`;}
  function hash(text){let value=2166136261;for(let i=0;i<text.length;i+=1)value=Math.imul(value^text.charCodeAt(i),16777619);return value>>>0;}
  function shuffle(items,seedText){const copy=items.slice();let seed=hash(seedText);const random=()=>{seed+=0x6D2B79F5;let t=seed;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};for(let i=copy.length-1;i>0;i-=1){const j=Math.floor(random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
  function eligible(program){const runtime=Number(program&&program.runtimeSeconds);return !!(program&&program.cleared&&program.videoId&&Number.isFinite(runtime)&&runtime>=120);}
  function createDaySchedule(nowMs,catalog){const p=stationParts(new Date(nowMs));const midnightMs=zonedToUtc(p.year,p.month,p.day);const daySeconds=86400;const key=dateKey(nowMs);const library=(Array.isArray(catalog)?catalog:[]).filter(eligible);if(!library.length)throw new Error("No playable vintage Disney programs.");const ordered=shuffle(library,`disney-vintage:${key}`);const schedule=[];let cursor=0,index=0;while(cursor<daySeconds&&index<500){const movie=ordered[index%ordered.length];const remaining=daySeconds-cursor;const blockSeconds=Math.min(Math.max(120,Math.floor(movie.runtimeSeconds)),remaining);const startsAtMs=midnightMs+cursor*1000;schedule.push({id:`${key}-${String(index).padStart(3,"0")}`,movie,startsAtMs,endsAtMs:startsAtMs+blockSeconds*1000,blockSeconds,fullStationSeconds:blockSeconds});cursor+=blockSeconds;index+=1;}return schedule;}
  function createSegments(block){return [{kind:"movie",title:block.movie.title,videoId:block.movie.videoId,cleared:true,sourceStart:0,stationStart:0,duration:block.blockSeconds}];}
  function resolve(nowMs,schedule){const block=schedule.find(item=>nowMs>=item.startsAtMs&&nowMs<item.endsAtMs)||schedule[schedule.length-1]||schedule[0];const blockElapsed=Math.max(0,Math.min(block.blockSeconds-1,Math.floor((nowMs-block.startsAtMs)/1000)));const segment=createSegments(block)[0];return {block,segment,segmentElapsed:blockElapsed,blockElapsed,mediaSeconds:blockElapsed,segmentRemaining:Math.max(0,block.blockSeconds-blockElapsed),movieReturnsIn:0,blockRemaining:Math.max(0,block.blockSeconds-blockElapsed)};}
  root.HermitEngine={TIME_ZONE,stationParts,zonedToUtc,dateKey,stationDurationSeconds:block=>block&&block.blockSeconds||1800,createDaySchedule,createSegments,resolve};
})(window);